import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Toaster } from 'react-hot-toast'


export const metadata = {
  title: 'TR Truck Lines',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster/>
        <Navbar/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}
